name: publish

on:
  release:
    types: [released]

jobs:
  npm:
    uses: oclif/github-workflows/.github/workflows/npmPublish.yml@main
    with:
      tag: latest
      githubTag: ${{ github.event.release.tag_name || inputs.tag }}
    secrets: inherit
