name: publish

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: yarn install --frozen-lockfile && yarn build
      - name: Publish package on NPM 📦
        run: |
          yarn config set version-tag-prefix "v"
          yarn config set version-git-tag false
          echo "RELEASE_VERSION: ${{ github.event.release.tag_name }}"
          yarn version --new-version ${{ github.event.release.tag_name }}
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
